//
// Created by Joel on 24/11/2025.
//

#ifndef CLIENTETCP_CONSTANTS_H
#define CLIENTETCP_CONSTANTS_H

#define PORT 8080
#define BUFFER_SIZE 1024

#define NUM_PLATFORMS 12
#define NUM_VINES 14
#define MAX_FRUITS 100



#endif //CLIENTETCP_CONSTANTS_H